app/app/urls.py
# from rest_framework import permissions
# from drf_yasg.views import get_schema_view
# from drf_yasg import openapi
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path, re_path
# from rest_framework import permissions
# from drf_yasg.views import get_schema_view
# from drf_yasg import openapi
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path, re_path
from rest_framework import permissions
from django.views.generic import TemplateView



urlpatterns = [
    path("", include("users.urls", namespace="users")),
    path("tokens/", include("tokens.urls", namespace="tokens")),
    path(
        'admin/login/',
        lambda r: redirect(
            f"/auth?{r.META['QUERY_STRING']}" if r.META['QUERY_STRING'] \
            else '/auth'
        )
    ),
    path("admin/", admin.site.urls),
    path('swagger-ui/', TemplateView.as_view(
        template_name='swagger-ui.html',
        extra_context={'schema_url': 'openapi-schema'}
    ), name='swagger-ui'),
    
]

app/tokens/urls.py
from django.urls import path
from tokens import views

app_name = "tokens"

urlpatterns = [
    path("activate/", views.ActivateToken.as_view(), name='activate'),
]

app/tokens/models.py
from datetime import datetime

from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.crypto import get_random_string

User = get_user_model()

def get_random_token6():
    return get_random_string(length=6)

class Token(models.Model):
    id = models.CharField(
         primary_key = True,
         default = get_random_token6,
         unique=True,
         max_length=6)
    
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="token",
        verbose_name="владелец",
    )
    
    def __str__(self):
        return str(self.id) 
    
    @receiver(post_save, sender=User) 
    def create_user_token(sender, instance, created, **kwargs):
        if created:
            Token.objects.create(user=instance)
    
class TokenActivated(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="token_activated",
        unique=True
    )
    token = models.ForeignKey(
        Token,
        on_delete=models.SET_NULL,
        related_name="users",
        verbose_name="владелец",
        null=True
    )
    date = models.DateTimeField(default=datetime.now, blank=True)

app/tokens/forms.py
from django.forms import CharField, Form


def validate_token(token):
    return len(token)==6
    
class TokenFormActivate(Form):
    token = CharField(validators=[validate_token])

app/tokens/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.views import View

from .forms import TokenFormActivate
from .models import Token, TokenActivated


class ActivateToken(LoginRequiredMixin, View):
    form_class = TokenFormActivate

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = request.user
            if Token.objects.filter(id=form.cleaned_data.get('token')).exists():
                token = Token.objects.get(id=form.cleaned_data.get('token'))
                if token.user == self.request.user:
                    request.session['form_err'] = 'Ошибка токена! Свой токен нельзя использовать'
                elif TokenActivated.objects.filter(user=user).exists:
                    request.session['form_err'] = 'Ошибка токена! У пользователя токен уже активирован'
                else:
                    token.users.create(user=user)
                return redirect('users:profile')
        request.session['form_err'] = 'Ошибка токена! Такого нет!'
        return redirect('users:profile')

app/templates/tokens/activate.html
{% load static %}
<div class='text-center p-3 bg_white'>
    Ваш токен: {{ request.user.token }}
</div>
{% if token_activated %}
    <div class='text-center p-3 bg_white'>
        Вы активировали токен: {{ token_activated.token }} <br>
        <div class='text-smoll'>
        {{ token_activated.date }} <br>
        Владелец: {{ token_activated.token.user }}
        </div>
    </div>
{% else%}
    <div class="registration-cssave">
    <form method='POST' action="{% url 'tokens:activate' %}">
        {% csrf_token %}
        <h3 class="text-center">Активация инвайт-кода</h3>

        <div class="form-group">
            <input class="form-control item" name="token" id="token" placeholder="XXXXXXXX" required>
            <div>
                {% if form_err %}
                 {{form_err}}
                {% endif %}
            </div>
        </div>
        <div class="form-group">
            <button class="btn btn-primary btn-block create-account" type="submit">Активация</button>
        </div>
    </form>
{% endif %}

app/templates/tokens/list.html
{% if users|length > 0 %}
<table class="table table-hover table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Телефон</th>
      <th scope="col">Дата</th>
    </tr>
  </thead>
  <tbody>
    {% for token_info in users%}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ token_info.user }}</td>
      <td>{{ token_info.date }}</td>
      
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endif %}