app/app/urls.py
# from rest_framework import permissions
# from drf_yasg.views import get_schema_view
# from drf_yasg import openapi
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path, re_path
# from rest_framework import permissions
# from drf_yasg.views import get_schema_view
# from drf_yasg import openapi
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path, re_path
from rest_framework import permissions
from django.views.generic import TemplateView



urlpatterns = [
    path("", include("users.urls", namespace="users")),
    path("tokens/", include("tokens.urls", namespace="tokens")),
    path(
        'admin/login/',
        lambda r: redirect(
            f"/auth?{r.META['QUERY_STRING']}" if r.META['QUERY_STRING'] \
            else '/auth'
        )
    ),
    path("admin/", admin.site.urls),
    path('swagger-ui/', TemplateView.as_view(
        template_name='swagger-ui.html',
        extra_context={'schema_url': 'openapi-schema'}
    ), name='swagger-ui'),
    
]

app/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from users import views

app_name = "users"

urlpatterns = [
    path("", views.ProfileUserPage.as_view(), name='profile'),
    path("auth/", views.AuthUserByTelPage.as_view(), name='auth'),
    path("logout/", LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

app/templates/includes/header.html
{% load static %}

<nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand">
        <img src="{% static 'img/icon.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:green">Refferral</span>System
      </a>
        {%if user.is_authenticated %}
        <div class='text-center '>
            Пользователь : {{ request.user }}
        </div>
        {% endif %}

      <ul class="nav nav-pills">
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" href="https://github.com/Alset-Nikolas" >Об авторе</a>
        </li>
       
        {%if user.is_authenticated %}
        
        
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'users:logout' %}active{% endif %}" href={% url 'users:logout' %}>Выйти</a>
        </li>
      
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'users:login' %}active{% endif %}  link-light"  href={% url 'users:auth' %}>Войти</a>
        </li>
        
        {% endif %}
      </ul>
    </div>
  </nav>   